# For more information about each property, visit the GitHub documentation: https://github.com/krausefx/deliver

########################################
# App Metadata
########################################

# The app identifier is required
app_identifier "com.banditthecat.BanditTheCat"
apple_id "963991661"

screenshots_path "./screenshots/"
config_json_folder './deliver'

version '1.0.0' # you can pass this if you want to verify the version number with the ipa file

app_icon '../Icons/Icon-1024.png'

copyright "#{Time.now.year} RokkinCat"

app_review_information({
  first_name: "Josh",
  last_name: "Holtz",
  phone_number: "1234567890",
  email_address: "github@rokkincat.com",
  demo_user: "cat",
  demo_password: "stuff",
  notes: "Just cat stuff"
})

primary_category "Business"
secondary_category "Books"

########################################
# Building and Testing
########################################

ipa "../BanditTheCat.ipa" # Tell 'Deliver' where it can find the finished ipa file
