# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

require 'dotenv'
Dotenv.load

before_all do

  # Increments build number of your project
  increment_build_number

  # Makes sure all cocoapods are up to date
  cocoapods

  # Runs unit tests
  # - argumnets passed as array of strings
  # - Docs on xctool (https://github.com/facebook/xctool)
  xctool ["-workspace BanditTheCat.xcworkspace", "-scheme BanditTheCat"]

end

lane :test do

  # Takes all screenshots for you (so magical)
  # - Configurations are in Snapfile
  # - Steps are defined in the snapshot.js
  snapshot

end

lane :beta do
  # snapshot
  # sigh
  # deliver :skip_deploy, :beta
  # sh "your_script.sh"
end

lane :deploy do
  # snapshot
  # sigh
  # deliver :skip_deploy, :force
  # frameit
end

lane :inhouse do
  # insert your code here
end

# You can define as many lanes as you want

after_all do |lane|

  # Create message for slack 
  message = nil
  case lane
  when :beta
    message = "beta build"
  when :inhouse
    message = "inhouse build"
  end

  # Sebd nessage to slack
  if message
    slack({
     message: message,
     success: true,
    })
  end

end


error do |lane, exception|
  # Something bad happened
end